apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluegreen
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/guilhermefaleiros/argocd-labs.git
    targetRevision: HEAD
    path: bluegreen/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: bluegreen
  syncPolicy: # Politicas de sincronização
    syncOptions:
      - CreateNamespace=true # Cria o namespace, caso não exista
    automated: # Configurações referente a automação da sincronização
      selfHeal: true # Aplica as configurações caso tenha alteração no repositório a cada 3 min
      prune: true # Remove elementos na sincronização
